version: '3.8'

services:
  app:
    build: .
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cardmanager
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Svatzapomni1
      - JWT_SECRET=$3crtCaRdMa3tew96y68uHeq8j1s2azWSz
      - ENCRYPTION_KEY=AbGSDb8gveqPVB9z
    depends_on:
      - db
    networks:
      - card-network

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cardmanager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Svatzapomni1
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - card-network

volumes:
  postgres-data:

networks:
  card-network:
    driver: bridge 